---
   - name: Install bottle python package
     pip:
       name: ansible-cmdb
   
   - name: Create a directory /out if it does not exist
     ansible.builtin.file:
        path: /out
        state: directory
        mode: '0755'
        owner: nobody
        group: nogroup

   - name: Install bottle python package
     command:ansible -m setup --tree out/ all

