---
   - name: check if pip3 is present in apt-repo
     apt:
       name: ['python3-pip','python3']
       state: present
       
   - name: Install ansible-cmdb python package
     pip:
       name: ansible-cmdb

   - name: Create a directory /out if it does not exist
     ansible.builtin.file:
        path: /out
        state: directory
        mode: '0755'
        owner: nobody
        group: nogroup

   - name: Install bottle python package
     command: ansible -m setup --tree out/ all
