---
  # source: https://github.com/dim-an/cod
  # https://www.linuxuprising.com/2020/02/cod-new-command-line-autocomplete.html
  - name: Download cod binary
    get_url:
       url: https://github.com/dim-an/cod/releases/download/v0.0.0/cod-Linux.tgz
       dest: /tmp/cod-Linux.tgz
       
        
   
  - name: unpack - tar -xvf cod-Linux.tgz
    ansible.builtin.unarchive:
       src: /tmp/cod-Linux.tgz
       dest: /tmp/
   
  - name: add 'echo "source <(cod init \$\$ bash)" |tee -a ~/.bashrc'
    command: 'echo "" |tee -a ~/.bashrc'

  - name: copy cod binary to usr/bin
    command: cp /tmp/cod-Linux/cod /usr/bin/.
     
  - name: Update hosts
    lineinfile:
        path:  ~/.bashrc
        state: present
        line: "{{ item }}"
    with_items:
          - 'source <(cod init $$ bash)'
