---
  # source: https://github.com/dim-an/cod
  - name: Download cod binary
    get_url:
       url: https://github.com/dim-an/cod/releases/download/v0.0.0/cod-Linux.tgz
       dest: /tmp/cod-Linux.tgz
       
  - name: unpack
    ansible.builtin.unarchive:
       src: /tmp/cod-Linux.tgz
       dest: /tmp/cod
   
  - name: add 'echo "source <(cod init $$ bash)" |tee -a ~/.bashrc'
    command: 'echo "source <(cod init $$ bash)" |tee -a ~/.bashrc'

  - name: copy cod binary to usr/bin
    command: cp /tmp/cod/cod-Linux/cod /usr/bin/.
     
