---
   - name: Check  '{{ item }}' docker-image is installed
     command: docker images
     register: docker_images
     
   - block:
      - name: "end play if nothing to upgrade"
        debug:
          msg: "nothing to upgrade, ending play"

      - meta: end_play
     when: docker_images.stdout.find('{{ item }}') != -1

   - name: log in to dockerhub for installing '{{ item }}' docker-image
     community.docker.docker_login:
        state: present
        registry_url: "https://index.docker.io/v1/" # dockerhub
        username: "{{ user }}"
        password: "{{ pass }}"

   - name: Pull '{{ item }}' docker-image from dockerhub
     community.docker.docker_image:
       name: "{{ item }}"
       source: pull
       state: present
