---
   - name: Check docker is installed
     command: docker images
     register: docker_images

   - name: log in to dockerhub
     community.docker.docker_login:
        state: present
        registry_url: "https://index.docker.io/v1/" # dockerhub
        username: "{{ user }}"
        password: "{{ pass }}"
     when: docker_images.stdout.find('{{ item }}') != 1

   - name: Pull image from dockerhub
     community.docker.docker_image:
       name: "{{ item }}"
       source: pull
       state: present
     when: docker_images.stdout.find('{{ item }}') != 1
