
---
  - name: ufw configure samba
    command: ufw allow {{ item }}
    with_items:
      - 137
      - 138
      - 139
      - 445
      - 8182
    
  - name: Create The directory share if it does not exist
    ansible.builtin.file:
        path: /share
        state: directory
        mode: '0755'
        owner: nobody
        group: nogroup

  - name: Install samba packages
    apt:
       name: ['samba-common','samba','samba-client']
       state: present

  - name: Update smb.conf
    lineinfile:
        path: /etc/samba/smb.conf
        state: present
        line: "{{ item }}"
    with_items:
          - '[share]'
          - 'path = /share'
          - 'writable = yes'
          - 'browsable = yes'
          - 'read only = no'
          - 'force user = nobody'
          - 'force create mode = 0777'
          - 'force directory mode = 0777'
          - 'guest only = yes'
          - 'guest ok = yes'

  - name: set read-write recurse
    command: chmod 0775 /share/ -R

  - name: set ownership recurse
    command: chown nobody:nogroup /share/ -R

  - name: Ensure Samba is running and set to start on boot.
    service: 
      name: smbd
      restarted: force
      enabled: yes
