---
   #source :https://gist.github.com/joshschmelzle/6aa786e5da37eea77b4bf0fcf85c3881
   - name: install tftp server
     apt:
       name: ['tftpd-hpa','tftp']
       state: present

   - name: Create a directory /data/tftp if it does not exist
     ansible.builtin.file:
        path: /data/tftp
        state: directory
        mode: '0777'
        owner: nobody
        group: nogroup

   - name: update tftpd-hpa
     lineinfile:
        path: /etc/default/tftpd-hpa
        state: present
        line: "{{ item }}"
     with_items:
          - 'TFTP_USERNAME="tftp"'
          - 'TFTP_DIRECTORY="/data/tftp"'
          - 'TFTP_ADDRESS=":69"'
          - 'TFTP_OPTIONS="--secure -v --create"'


   - name: ufw service enabled 
     service:
        name: ufw
        state: enabled 
     become: true

   - name: ufw configure tftp
     command: ufw allow tftp

   - name: restart tftpd-hpa
     service:
       name: tftpd-hpa
       state: restarted
     become: true
     
   - name: ufw service restarted
     service:
        name: ufw
        state: restarted
     become: true

  - name: Creates directory /images
    file:
       path: /images
       state: directory
         
  - name: Download ubuntu server image
    get_url:
       url: https://releases.ubuntu.com/20.04/ubuntu-20.04.1-live-server-amd64.iso
       dest: /data/tftp/boot/ubuntu-20.04.1-live-server-amd64.iso

  - name: Extract kernel and ramdisk from a LiveCD
    community.general.iso_extract:
      image: /images/ubuntu-20.04.1-live-server-amd64.iso
      dest: /data/tftp/boot
      files:
      - isolinux/kernel
      - isolinux/initrd.cgz
      - casper/initrd
      - casper/vmlinuz
 
 - name: Download Grub image 
   get_url:
       url: http://archive.ubuntu.com/ubuntu/dists/focal/main/uefi/grub2-amd64/current/grubnetx64.efi.signed
       dest: /data/tftp/boot/pxelinux.0
