# cat >> base.yml << #eof
---
- name: base ansible playbook
  hosts: localhost
  tasks:
      
    - name: Gather the packager facts
      package_facts:
        manager: apt
    
    - name: Print the package facts
      debug:
        var: ansible_facts.packages
    
    - name: Create a Samba-share folder
      include: tasks/sambashare.yml
      when: "'samba-common' not in ansible_facts.packages"
       
    - name: include docker install if not installed
      include: tasks/docker_install.yml
      when: "'docker-ce' not in ansible_facts.packages"
     
    - name: include docker install if not installed
      include: tasks/docker_pull.yml
      with_items:
        - "mysql"
        - "portainer/portainer"
        - "nodered/node-red"
        - "grafana/grafana"
        - "influxdb"
        

   
