# cat >> base.yml << #eof
---
- name: base ansible playbook
  hosts: localhost
  tasks:

    - name: Show facts available on the system
      ansible.builtin.debug:
        var: ansible_facts
      
    - name: include docker install if not installed
      include: tasks/docker_pull.yml
      with_items:
        - "mysql"
        - "portainer/portainer"
        - "nodered/node-red"
        - "grafana/grafana"
        - "influxdb"
