---
- name:  install checkmk
  hosts: localhost
  vars:
    checkmk_url_deb : https://download.checkmk.com/checkmk/1.6.0p20/check-mk-raw-1.6.0p20_0.focal_amd64.deb
    sitename : monitor
    admin_password : bomber-safe
  tasks:
  
    - name: Import a key from a checkmk APT repository
      ansible.builtin.apt_key:
        url: https://download.checkmk.com/checkmk/Check_MK-pubkey.gpg
        state: present
      
    - name: apt install git if not present
      apt:  
       name: ['openssh-server','dpkg-sig','gdebi-core']
       state: present

    - name: install check-mk deb file
      apt: 
        deb: "{{ checkmk_url_deb }}"
        state: present
        
    - name: Create {{ sitename }}
      command: omd create {{ sitename }}

    - name: Set admin password
      command: "htpasswd -b /opt/omd/sites/{{ sitename }}/etc/htpasswd omdadmin '{{ admin_password }}'"
      become: true
      when: admin_password is defined

    - name: Restart site
      command: "omd restart {{ sitename }}"
      become: true
