# cat >> chef-workstation.yml << #eof
---
  # https://docs.chef.io/quick_start/
- name: chef-workstation installation playbook
  hosts: localhost
  vars:
  tasks:
  
    - name: Install ruby
      apt:  
       name: ['ruby']
       state: present

    - name: install chef-workstation deb file
      apt:
        deb: https://packages.chef.io/files/stable/chef-workstation/21.1.233/ubuntu/20.04/chef-workstation_21.1.233-1_amd64.deb
        state: present
        
    - name: Create a directory /share/cookbooks if it does not exist
      ansible.builtin.file:
        path: /share/cookbooks
        state: directory
        mode: '0755'
        owner: nobody
        group: nogroup

        
    - name: Install samba packages
      apt:  
       name: ['samba-common','samba','samba-client']
       state: present
     
    - name: Ensure Samba is running and set to start on boot.
      service: "name=smbd state=started enabled=yes"
    
    - name: Update hosts
      lineinfile:
        path: /etc/samba/smb.conf
        state: present
        line: "{{ item }}"
      with_items:
          - '[share]'
          - 'path = /share'
          - 'writable = yes'
          - 'browsable = yes'
          - 'read only = no'
          - 'force user = nobody'
          - 'force create mode = 0777'
          - 'force directory mode = 0777'
          - 'guest only = yes'
          - 'guest ok = yes'
          
    - name: set read-write recurse
      command: chmod 0775 /share/ -R
 
    - name: set read-write recurse
      command: chown nobody:nogroup /share/ -R
     
    - name: restart smbd
      service:
        name: smbd
        state: restarted
      become: true
