# cat >> chef-workstation.yml << #eof
---
  # https://docs.chef.io/quick_start/
- name: chef-workstation installation playbook
  hosts: localhost
  vars:
  tasks:
  
    - name: Install ruby
      apt:  
       name: ['ruby']
       state: present

    - name: install chef-workstation deb file
      apt:
        deb: https://packages.chef.io/files/stable/chef-workstation/21.1.233/ubuntu/20.04/chef-workstation_21.1.233-1_amd64.deb
        state: present
        
    - name: Install samba packages
      apt:  
       name: ['samba-common','samba','samba-client']
       state: present
     
    - name: Ensure Samba is running and set to start on boot.
      service: "name=smbd state=started enabled=yes"

    - name: Update hosts
      lineinfile:
        path: /etc/hosts
        state: present
        line: "{{ item }}"
        with_items:
          - '[cookbooks]'
          - 'path = /cookbooks'
          - 'writable = yes'
          - 'browsable = yes'
          - 'read only = no'
          - 'force user = nobody'

