# cat >> chef-workstation.yml << #eof
---
  # https://docs.chef.io/quick_start/
- name: chef-workstation installation playbook
  hosts: localhost
  vars:
  tasks:

    - name: install chef-workstation deb file
      apt:
        deb: https://packages.chef.io/files/stable/chef-workstation/21.1.233/ubuntu/20.04/chef-workstation_21.1.233-1_amd64.deb
        state: present
        
    - name: Creates cookbooks Directory
      file:
        path: /cookbooks/first_cookbook/recipes
        state: directory
        
           
    - name: Insert content to file
      blockinfile:
        block: " file \"#{ENV['HOME']}/test.txt\" do \n     content 'This file was created by Chef Infra!'\n end"
        path: /cookbooks/first_cookbook/recipes/default.rb
#eof
