---
- name: install mysql docker image
  hosts: localhost
  tasks:
    - name: Load image from archive and push to a private registry
      community.general.docker_image:
        - name: mysql
          tag: v5.7
          source: pull
