---
- name : installing docker - compose
  # source:  https://graspingtech.com/install-docker-ansible/
  hosts: localhost
  become: yes
  tasks:

    - name: Update apt cache
      apt: update_cache=yes cache_valid_time=3600

    #- name: Upgrade all apt packages
    #  apt: upgrade=dist
 
    - name: Install dependencies
      apt:  
       name: ['apt-transport-https','ca-certificates','curl','software-properties-common','gnupg-agent']
       state: present
       
       
    - name: Add Docker APT repository
      apt_repository:
         repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        
    - name: Update apt cache
      apt: update_cache=yes cache_valid_time=3600
    
    - name: Install Docker ce
      apt:  
       name: ['docker-ce','docker-ce-cli ','containerd.io']
       state: present

    - name: Install docker-compose and prerequisites for docker-compose
      apt:
        name: ['python3-pip', 'python3-setuptools', 'virtualenv','docker-compose']
        state: present
