---
- name: This is a hello-world example
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Create a file called '/tmp/testfile.txt' with the content 'hello world'.
      copy:
        content: hello world
        dest: /tmp/testfile.txt
