# cat >> iotstack.yml << #eof
---
- name: install mysql docker image
  hosts: localhost
  vars:
    username : user
    pass : password
  tasks:

    - name: log in to dockerhub
      community.docker.docker_login:
        state: present
        registry_url: "https://index.docker.io/v1/" # dockerhub
        username: {{ user }}
        password: {{ pass }}

    - name: Pull homeassistant image
      community.docker.docker_image:
       name: "homeassistant/home-assistant"
       source: pull
       state: present
   
    - name: Pull portainer image
      community.docker.docker_image:
       name: "portainer/portainer"
       source: pull
       state: present
  
    - name: Pull nodered/node-red image
      community.docker.docker_image:
       name: "nodered/node-red"
       source: pull
       state: present
     
    - name: Pull nodered/node-red image
      community.docker.docker_image:
       name: "nodered/node-red"
       source: pull
       state: present
       
    - name: Pull grafana image
      community.docker.docker_image:
       name: "grafana/grafana"
       source: pull
       state: present

    - name: Pull influxdb image
      community.docker.docker_image:
       name: "influxdb"
       source: pull
       state: present
       
    - name: Re-create a redis container
      community.general.docker_container:
       name: myredis
       image: influxdb
       command: redis-server --appendonly yes
      state: present
      recreate: yes
      exposed_ports:
        - 6379
      volumes_from:
        - mydata
#eof
