# cat >> iotstack.yml << #eof
---
- name: install mysql docker image
  hosts: localhost
  tasks:

    - name: log in to dockerhub
      community.docker.docker_login:
        state: present
        registry_url: "https://index.docker.io/v1/" # dockerhub
        username: "{{ user }}"
        password: "{{ pass }}"

    - name: Pull homeassistant image
      community.docker.docker_image:
       name: "homeassistant/home-assistant:stable"
       source: pull
       state: present
   
    - name: Pull portainer image
      community.docker.docker_image:
       name: "portainer/portainer"
       source: pull
       state: present
  
    - name: Pull nodered/node-red image
      community.docker.docker_image:
       name: "nodered/node-red"
       source: pull
       state: present
       
    - name: Pull grafana image
      community.docker.docker_image:
       name: "grafana/grafana"
       source: pull
       state: present

    - name: Pull influxdb image
      community.docker.docker_image:
       name: "influxdb"
       source: pull
       state: present
       
    - name: Create homeassistant container
      docker_container:
       name: hassio
       image: homeassistant/home-assistant
       network_mode: host
       exposed_ports:
         - 8123
       state: started
       restart: yes
       
    - name: Allow port 8123
      community.general.ufw:
          rule: allow
          port: 8123
          proto: tcp
       
    - name: Create portainer container
      docker_container:
       name: portainer
       image: portainer/portainer
       volumes:
          - /var/run/docker.sock:/run/containerd/containerd.sock
       network_mode: host
       exposed_ports:
         - 9000
       state: started
       restart: yes
       
    - name: Allow port 9000
      community.general.ufw:
        rule: allow
        port: 9000
        proto: tcp
#eof
