---
- name: list packages
  hosts: localhost
  tasks:
  
   - name: Gather the package facts
     package_facts:
     manager: auto

   - name: Print the package facts
     debug:
     var: ansible_facts.packages
