---
- name: install mysql docker image
  hosts: localhost
  tasks:
  
  
   - name: include docker install if not installed
     include: tasks/docker_pull.yml
     with_items:
        - "portainer/portainer"
        - "postgres:9.6.21"
 
