---
- name:  install virtualbox and vagrant if not present (ubuntu 20.04)
  hosts: localhost
  tasks:
    - name: apt install virtualbox and vagrant if not present
      apt:  
       name: ['virtualbox','virtualbox-ext-pack','virtualbox-qt']
       state: present
