---
- name:  install virtualbox and vagrant if not present (ubuntu 20.04)
  hosts: localhost
  vars:
    virtualboxsource: 
  tasks:
    - name: apt install git if not present
      apt:  
       name: ['git','mlocate']
       state: present
    - name: install deb file from virtualbox.org
      apt:
        deb: https://download.virtualbox.org/virtualbox/6.1.16/virtualbox-6.1_6.1.16-140961~Ubuntu~eoan_amd64.deb
        state: present
    - name: Remove useless packages from the cache
      apt:
          autoclean: yes
    - name: Creates directory /images
      file:
         path: /images
         state: directory
    - name: Download file from a file path
      get_url:
       url: https://download.virtualbox.org/virtualbox/6.1.16/VBoxGuestAdditions_6.1.16.iso
       dest: /images/VBoxGuestAdditions_6.1.16.iso
    - name: Download file from a file path
      get_url:
       url: https://releases.ubuntu.com/20.04/ubuntu-20.04.1-live-server-amd64.iso
       dest: /images/ubuntu-20.04.1-live-server-amd64.iso



