---
- name:  install virtualbox and vagrant if not present (ubuntu 20.04) by using this script you're accpeting the licence agreement of Virtualbox.org
  hosts: localhost
  vars:
    ubuntu_url : https://releases.ubuntu.com/20.04/ubuntu-20.04.1-live-server-amd64.iso
  tasks:
    
    - name: Gather the packager facts
      package_facts:
        manager: apt
   
    - name: Create a Samba-share folder
      include: tasks/sambashare.yml
      when: "'samba-common' not in ansible_facts.packages"
      
    - name: apt install git if not present
      apt:  
       name: ['git','mlocate']
       state: present
      when: "'mlocate' not in ansible_facts.packages"
      
    - name: install deb file from virtualbox.org
      apt:
        deb: https://download.virtualbox.org/virtualbox/6.1.16/virtualbox-6.1_6.1.16-140961~Ubuntu~eoan_amd64.deb
        state: present
      when: "'virtualbox' not in ansible_facts.packages"
      
      
    - name: Remove useless packages from the cache
      apt:
          autoclean: yes
    - name: Creates directory /images
      file:
         path: /images
         state: directory
         
    - name: Download Guestimage iso
      get_url:
       url: https://download.virtualbox.org/virtualbox/6.1.16/VBoxGuestAdditions_6.1.16.iso
       dest: /images/VBoxGuestAdditions_6.1.16.iso
       
    - name: Download ubuntu server image
      get_url:
       url: "{{ ubuntu_url }}"
       dest: /images/ubuntu-20.04.1-live-server-amd64.iso
   
   
    - name: Gather the packager facts
      command: VBoxManage list extpacks
        register: Vbox_extpacks

    - block:
      - name: Download Extention Pack
        get_url:
          url:  https://download.virtualbox.org/virtualbox/6.1.16/Oracle_VM_VirtualBox_Extension_Pack-6.1.16-140961.vbox-extpack
          dest: /images/Oracle_VM_VirtualBox_Extension_Pack-6.1.16-140961.vbox-extpac
   
      - name: install extentionpack
        command: VBoxManage extpack install /images/Oracle_VM_VirtualBox_Extension_Pack-6.1.16-140961.vbox-extpack --accept-license=33d7284dc4a0ece381196fda3cfe2ed0e1e8e7ed7f27b9a9ebc4ee22e24bd23c         
      
      when: Vbox_extpacks.stdout.find('virtualbox') != -1

      
    - name: Extention pack cleanup
      command: VBoxManage extpack cleanup




