---
- name: This fixes broadcom driver issues
  hosts: localhost
  gather_facts: False
  tasks:
    - name: install dev packages for statd build
      apt:  
       name: ['broadcom-sta-common','broadcom-sta-dkms']
       state: present
